application:
  # DB 설정
  database:
    mariadb:
      master:
        url: jdbc:mariadb://localhost:13306/dev_base?characterEncoding=UTF-8&serverTimezone=UTC
        username: dev_base
        password: base1234!@
        driver-class-name: org.mariadb.jdbc.Driver
      slave:
        url: jdbc:mariadb://localhost:13307/dev_base?characterEncoding=UTF-8&serverTimezone=UTC
        username: dev_base
        password: base1234!@
        driver-class-name: org.mariadb.jdbc.Driver
      #   database:
      #    mariadb:
      #      master:
      #        url: jdbc:mariadb://${DB_MASTER_HOST}:${DB_MASTER_PORT}/${DB_MASTER_DATABASE}?useUnicode=true&characterEncoding=utf8mb4&autoReconnect=true&allowMultiQueries=true
      #        username: ${DB_MASTER_USERNAME}
      #        password: ${DB_MASTER_PASSWORD}
      #        driver-class-name: org.mariadb.jdbc.Driver
      #      slave:
      #        url: jdbc:mariadb://${DB_SLAVE_HOST}:${DB_SLAVE_PORT}/${DB_SLAVE_DATABASE}?useUnicode=true&characterEncoding=utf8mb4&autoReconnect=true&allowMultiQueries=true
      #        username: ${DB_SLAVE_USERNAME}
      #        password: ${DB_SLAVE_PASSWORD}
      #        driver-class-name: org.mariadb.jdbc.Driver
  # redis 설정
  redis:
    host: localhost
    port: 16379
  # AWS S3 설정
  aws:
    s3:
      cdn-bucket:
        bucket-name: cdn.xxxx.xxx
        upload-path:
          event: event/
    sqs:
      test-queue: test
spring:
  # AWS secrets-manager 설정
#  config:
#    import:
#      - optional:aws-secretsmanager:dev/settlement-management



