application:
  database:
    mariadb:
      master:
        url: jdbc:mariadb://localhost:13306/base?characterEncoding=UTF-8&serverTimezone=UTC
        username: base
        password: base1234!@
        driver-class-name: org.mariadb.jdbc.Driver
      slave:
        url: jdbc:mariadb://localhost:13307/base?characterEncoding=UTF-8&serverTimezone=UTC
        username: base
        password: base1234!@
        driver-class-name: org.mariadb.jdbc.Driver
  aws:
    s3:
      cdnbucket:
        bucket-name: cdn.fassto.ai
        upload-path:
          event: event/



