server:
  port: 9001

spring:
  application:
    name: management
  profiles:
    active: local
  main:
    banner-mode: off
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        use_sql_comments: true
    show-sql: true
  # devtools
  devtools:
    add-properties: false
    livereload:
      enabled: true
    restart:
      enabled: true
  # 가상 스레드 설정
  threads:
    virtual:
      enabled: true
management:
  # actuator 설정
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

