server:
  port: 9001

spring:
  application:
    name: management
  profiles:
    active: local
  main:
    banner-mode: off
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        use_sql_comments: true
    show-sql: true
  # devtools
  devtools:
    add-properties: false
    livereload:
      enabled: true
    restart:
      enabled: true
  # 가상 스레드 설정
  threads:
    virtual:
      enabled: true
management:
  # actuator 설정
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

application:
  # DB 설정
  database:
    mariadb:
      master:
        url: jdbc:mariadb://${DB_MASTER_HOST}:${DB_MASTER_PORT}/${DB_MASTER_DATABASE}?useUnicode=true&characterEncoding=utf8mb4&autoReconnect=true&allowMultiQueries=true
        username: ${DB_MASTER_USERNAME}
        password: ${DB_MASTER_PASSWORD}
        driver-class-name: org.mariadb.jdbc.Driver
      slave:
        url: jdbc:mariadb://${DB_SLAVE_HOST}:${DB_SLAVE_PORT}/${DB_SLAVE_DATABASE}?useUnicode=true&characterEncoding=utf8mb4&autoReconnect=true&allowMultiQueries=true
        username: ${DB_SLAVE_USERNAME}
        password: ${DB_SLAVE_PASSWORD}
        driver-class-name: org.mariadb.jdbc.Driver
  # redis 설정
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}

