server:
  port: 9001

spring:
  application:
    name: settlement-management
  profiles:
    active: local
  main:
    banner-mode: off
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  devtools:
    add-properties: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 500
    open-in-view: false
    show-sql: true
  cloud:
    aws:
      credentials:
        profile:
          name: default
      region:
        static: ap-northeast-2
management:
  # actuator 설정
  endpoints:
    web:
      exposure:
        include: health
      base-path: /management

