server:
  port: 9001

spring:
  application:
    name: settlement-management
  profiles:
    active: local
  main:
    banner-mode: off
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  devtools:
    add-properties: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 500
    open-in-view: false
    show-sql: true
  # 가상 스레드 설정
  threads:
    virtual:
      enabled: true
management:
  # actuator 설정
  endpoints:
    web:
      exposure:
        include: health
      base-path: /management

