application:
  # AWS S3 설정
  aws:
    s3:
      cdn-bucket:
        bucket-name: cdn.xxxx.xxx
        upload-path:
          event: event/
    sqs:
      test-queue: test
spring:
  # AWS secrets-manager 설정
  config:
    import:
      - optional:aws-secretsmanager:dev/management



